# config/local.yaml

env: "local" # Окружение - local, dev или prod
http_server: # конфигурация нашего http-сервера
  host: "localhost"
  port: "3030"
  timeout: 4s
  idle_timeout: 30s
db_config: # конфигурация базы данных
  host: "127.0.0.1"
  database: "apiwalk"
  username: "root"
  password: "password"